function session = wc4sm_create_session(state,metadata)
%WC4SM_CREATE_SESSION Create a versioned WCC4SM project/session structure.
% Missing state sections are filled with empty values so callers can save a
% partially completed workflow without inventing placeholder results.

    arguments
        state (1,1) struct = struct()
        metadata (1,1) struct = struct()
    end

    stateDefaults = struct( ...
        'Spectrum',struct(), ...
        'Peaks',struct([]), ...
        'PeakDataset',struct([]), ...
        'ReferenceLines',struct(), ...
        'CalibrationPairs',struct([]), ...
        'InitialCalibration',struct(), ...
        'FinalCalibration',struct(), ...
        'CalibrationModels',struct([]), ...
        'AppliedModel',struct(), ...
        'AppliedModelName','', ...
        'SetDesign',struct(), ...
        'PositionCrossValidation',struct(), ...
        'UISettings',struct());
    state = mergeKnownFields(stateDefaults,state);

    provenanceDefaults = struct('MasterLibrary','', ...
        'MasterVersion','','Authority','','WavelengthMedium','Unspecified', ...
        'SelectionMode','','SelectionModeVersion','','Notes','');
    metadataDefaults = struct('Operator','','InstrumentID','', ...
        'InstrumentModel','','MeasurementTime',NaT,'MeasurementFile','', ...
        'DarkFile','','Notes','','ReferenceProvenance',provenanceDefaults);
    metadata = mergeKnownFields(metadataDefaults,metadata);
    if ~isstruct(metadata.ReferenceProvenance) || ...
            ~isscalar(metadata.ReferenceProvenance)
        error('WCC4SM:InvalidReferenceProvenance', ...
            'ReferenceProvenance must be a scalar structure.');
    end
    metadata.ReferenceProvenance = mergeKnownFields( ...
        provenanceDefaults,metadata.ReferenceProvenance);

    session = struct('Application','WCC4SM','FormatVersion','1.0', ...
        'SoftwareVersion',wc4sm_version(),'CreatedAt',datetime('now'), ...
        'ModifiedAt',datetime('now'),'Metadata',metadata,'State',state);
end

function result = mergeKnownFields(defaults,input)
    result = defaults;
    names = fieldnames(input);
    for k = 1:numel(names)
        result.(names{k}) = input.(names{k});
    end
end
