function f = wc4sm_empty_final_model()
%WC4SM_EMPTY_FINAL_MODEL Create an empty final calibration model structure.
% Holds the polynomial fit (normalized + natural coefficients), the equation
% string, per-pair fit/LOO diagnostics and summary residual metrics.

    f = struct('valid',false,'PositionMethod','','Degree',NaN, ...
        'Coefficients',[],'Mu',[],'S',[],'NaturalCoefficients',[], ...
        'Equation','','PeakID',{{}},'Pixel',[],'ReferenceWavelength',[], ...
        'FittedWavelength',[],'Residual',[],'MeanResidual',NaN,'STD',NaN, ...
        'RMS',NaN,'MaxAbsResidual',NaN,'LOOResidual',[], ...
        'DeletionMaxCurveChange',[],'LOORMS',NaN,'LOOMaxAbs',NaN, ...
        'MaxDeletionInfluence',NaN);
end
